# Generated by Django 5.0.6 on 2024-07-31 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Checkpoint', '0005_rename_due_date_deadline_work_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deadline',
            old_name='work_date',
            new_name='due_date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='work_date',
            new_name='due_date',
        ),
    ]
